### ISSUE TITLE
Is CSS for language syntax highlighting inside Fenced Code Blocks available?

### ISSUE THREAD

**Issue by shurcooL** [primer/markdown#62]
Hi,

If I understand correctly, this repository looks like the CSS to support (GitHub Flavored) Markdown, and includes the CSS for things like headers, lists, tables, images, links, spacing and so on. That's great!

Does it also include CSS for syntax highlighting of languages inside [Fenced Code Blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)? For example, if I render the following Markdown document using the [raw Markdown rendering API endpoint](https://developer.github.com/v3/markdown/#render-a-markdown-document-in-raw-mode):

    Hello **world**.
    
    ```diff
    +added
    -removed
    ```
    
    ```Go
    err := http.ListenAndServe(":8080", mux)
    ```

Which can be done using the following `curl` command:

    $ curl -X POST -H 'Content-Type: text/x-markdown' https://api.github.com/markdown/raw -d $'Hello **world**.
    
    ```diff
    +added
    -removed
    ```
    
    ```Go
    err := http.ListenAndServe(":8080", mux)
    ```
    '

The response is:

```HTML
<p>Hello <strong>world</strong>.</p>

<div class="highlight highlight-source-diff"><pre><span class="pl-mi1">+added</span>
<span class="pl-md">-removed</span></pre></div>

<div class="highlight highlight-source-go"><pre><span class="pl-smi">err</span> <span class="pl-k">:=</span> http.<span class="pl-c1">ListenAndServe</span>(<span class="pl-s"><span class="pl-pds">"</span>:8080<span class="pl-pds">"</span></span>, mux)</pre></div>
```

Does this repository contain the neccessary CSS to style those classes such as `pl-mi1`, `pl-md`, `pl-c1`, `pl-s`, etc., to be able to render that Markdown to look like the following:

---

Hello **world**.

```diff
+added
-removed
```

```Go
err := http.ListenAndServe(":8080", mux)
```

---

If not, is it available somewhere else? Is it going to be available in the future?

Thank you!

**Comment by jonrohan** [comment]
> Does it also include CSS for syntax highlighting of languages inside Fenced Code Blocks?

Yes, actually there were just made available here https://github.com/primer/github-syntax-light.

**Comment by shurcooL** [comment]
Thanks!

**Comment by jonrohan** [comment]
Just realized my answer might not be clear. Yes, this repository is the markdown styling we use on github.com. No it doesn't automatically include the code highlighting. Yes, it's available https://github.com/primer/github-syntax-light
